import { Lesson } from '../types';

export const LESSON_BIOT_SAVART_AMPERES_LAW: Lesson = {
  id: 'lsn-ch8-biot-savart-amperes-law',
  topicId: 'ch8-biot-savart-amperes-law',
  chapterId: 'ch-inductors',
  order: 2,
  title: {
    en: 'Biot-Savart Law, Ampère\'s Circuital Law & Solenoid Fields',
    hi: 'बायो-सावर्ट नियम, एम्पियर का परिपथीय नियम एवं परिनालिका क्षेत्र',
    bn: 'বায়ো-সাভার্ট সূত্র, অ্যাম্পিয়ারের সার্কিটাল সূত্র ও সলিনয়েড ক্ষেত্র'
  },
  description: {
    en: 'Mathematical formulation of magnetic field generated by electric current: Biot-Savart law, Ampère\'s circuital law, magnetic field of straight wires, circular loops, solenoids, and toroids.',
    hi: 'विद्युत धारा द्वारा उत्पन्न चुंबकीय क्षेत्र का गणितीय निरूपण: बायो-सावर्ट नियम, एम्पियर का परिपथीय नियम, सीधे तार, वृत्ताकार लूप, परिनालिका एवं टोराइड का चुंबकीय क्षेत्र।',
    bn: 'তড়িৎ প্রবাহ দ্বারা সৃষ্ট চৌম্বক ক্ষেত্রের গাণিতিক সমীকরণ: বায়ো-সাভার্ট সূত্র, অ্যাম্পিয়ারের সার্কিটাল সূত্র, সোজা তার, বৃত্তাকার লুপ, সলিনয়েড ও টরয়েডের চৌম্বক ক্ষেত্র।'
  },
  easyExplanation: {
    en: 'Whenever electric current flows through a wire, it wraps an invisible magnetic field around itself. Ampère\'s and Biot-Savart\'s laws are the mathematical tools that allow engineers to calculate exactly how strong that magnetic field will be at any point around a coil, wire, or electromagnet.',
    hi: 'जब भी किसी तार में विद्युत धारा बहती है, तो वह अपने चारों ओर एक अदृश्य चुंबकीय क्षेत्र बना लेती है। एम्पियर और बायो-सावर्ट के नियम वे गणितीय उपकरण हैं जो इंजीनियरों को यह गणना करने की अनुमति देते हैं कि किसी कुंडली या तार के चारों ओर चुंबकीय क्षेत्र कितना मजबूत होगा।',
    bn: 'তারের মধ্য দিয়ে বিদ্যুৎ প্রবাহিত হলেই তার চারপাশে একটি অদৃশ্য চৌম্বক ক্ষেত্র আবর্তিত হয়। বায়ো-সাভার্ট এবং অ্যাম্পিয়ারের সূত্র হলো এমন গাণিতিক ভিত্তি যার সাহায্যে কোনো কয়েল, তার বা ইলেক্ট্রোম্যাগনেটের যেকোনো বিন্দুতে চৌম্বক ক্ষেত্রের মান নির্ভুলভাবে নির্ণয় করা যায়।'
  },
  detailedExplanation: {
    en: `1. Biot-Savart Law:
The magnetic field dB at a point P due to a small current element (I · dl) at distance r is:
dB = (μ / (4 · π)) · (I · dl × r̂) / r²
In scalar magnitude:
dB = (μ / (4 · π)) · (I · dl · sin θ) / r²
Where:
- μ = μ0 · μr is the magnetic permeability of the medium.
- θ is the angle between the current element dl and the position vector r.

2. Applications of Biot-Savart Law:
- At the center of a flat circular coil of N turns and radius R:
  B = (μ · N · I) / (2 · R)
- At an axial distance x from the center of a circular loop:
  B = (μ · N · I · R²) / [2 · (R² + x²)^(3/2)]

3. Ampère's Circuital Law:
Ampère's law states that the line integral of magnetic flux density B around any closed imaginary loop (Ampèrian loop) equals μ times the net enclosed current:
∮ B · dl = μ · I_enclosed = μ0 · μr · ∑ I

In terms of Magnetic Field Intensity (H):
∮ H · dl = I_enclosed = Magnetomotive Force (MMF) [Ampere-turns]

4. Magnetic Field of a Long Straight Conductor:
By choosing a circular Ampèrian loop of radius r around a long straight wire carrying current I:
B · (2 · π · r) = μ0 · I  ==>  B = (μ0 · I) / (2 · π · r)
H = I / (2 · π · r) [A/m]

5. Magnetic Field of a Solenoid:
An ideal long solenoid of length l with N total turns (n = N/l turns per meter) carrying current I has an almost perfectly uniform axial field inside:
B = μ0 · μr · (N · I) / l = μ0 · μr · n · I
H = n · I = (N · I) / l
At the very ends of a long solenoid: B_end = ½ · B_center.

6. Magnetic Field of a Toroid (Donut Ring):
A toroid of mean radius R (mean circumference l = 2πR) with N turns:
B = (μ0 · μr · N · I) / (2 · π · R)`,
    hi: `1. बायो-सावर्ट का नियम (Biot-Savart Law):
किसी सूक्ष्म धारा अल्पांश (I · dl) के कारण r दूरी पर स्थित बिंदु P पर चुंबकीय क्षेत्र:
dB = (μ0 / 4π) · (I · dl · sin θ) / r² [Tesla]

2. एम्पियर का परिपथीय नियम (Ampère's Circuital Law):
किसी बंद परिपथ के चारों ओर चुंबकीय क्षेत्र B का रेखीय समाकलन उस बंद लूप द्वारा परिबद्ध कुल विद्युत धारा का μ गुना होता है:
∮ B · dl = μ0 · I_enclosed
∮ H · dl = N · I = MMF

3. लंबे सीधे तार का चुंबकीय क्षेत्र:
तार से r लंबवत दूरी पर: B = (μ0 · I) / (2 · π · r)

4. परिनालिका (Solenoid) का आंतरिक चुंबकीय क्षेत्र:
लंबाई l, फेरों की संख्या N वाली परिनालिका के अंदर एकसमान क्षेत्र:
B = (μ0 · μr · N · I) / l = μ · n · I [टेस्ला]

5. टोराइड (Toroid):
औसत त्रिज्या R वाले टोराइड के कोर में: B = (μ0 · μr · N · I) / (2πR)।`,
    bn: `১. বায়ো-সাভার্ট সূত্র (Biot-Savart Law):
একটি ক্ষুদ্র তড়িৎ উপাদান (I · dl) থেকে r দূরত্বে অবস্থিত কোনো বিন্দুতে সৃষ্ট চৌম্বক ক্ষেত্র:
dB = (μ0 / 4π) · (I · dl · sin θ) / r² [টেসলা]

২. অ্যাম্পিয়ারের সার্কিটাল সূত্র (Ampère's Circuital Law):
যেকোনো বদ্ধ পথ বরাবর চৌম্বক ক্ষেত্র B এর রৈখিক সমাকলন ওই পথ দ্বারা আবদ্ধ মোট তড়িৎ প্রবাহের μ0 গুণের সমান:
∮ B · dl = μ0 · I_enclosed
∮ H · dl = N · I = MMF (চৌম্বক চালক বল)

৩. দীর্ঘ সোজা পরিবাহীর জন্য চৌম্বক ক্ষেত্র:
তার থেকে r দূরত্বে: B = (μ0 · I) / (2 · π · r)

৪. সলিনয়েডের (Solenoid) অভ্যন্তরে চৌম্বক ক্ষেত্র:
l দৈর্ঘ্য ও N পাকসংখ্যা বিশিষ্ট সলিনয়েডের কেন্দ্রে সুষম চৌম্বক ক্ষেত্র:
B = (μ0 · μr · N · I) / l = μ · n · I [টেসলা]

৫. টরয়েডের (Toroid) চৌম্বক ক্ষেত্র:
গড় ব্যাসার্ধ R হলে: B = (μ0 · μr · N · I) / (2πR)।`
  },
  formulas: [
    {
      expression: '∮ B · dl = μ0 · I_enclosed',
      description: {
        en: 'Ampère\'s Circuital Law in free space',
        hi: 'मुक्त आकाश में एम्पियर का परिपथीय नियम',
        bn: 'শূন্যস্থানে অ্যাম্পিয়ারের সার্কিটাল সূত্র'
      }
    },
    {
      expression: 'B = (μ0 · I) / (2 · π · r)',
      description: {
        en: 'Magnetic flux density around a long straight current-carrying wire',
        hi: 'सीधे धारावाही तार के चारों ओर चुंबकीय फ्लक्स घनत्व',
        bn: 'দীর্ঘ সোজা তড়িৎবাহী তারের চারপাশে ফ্লাক্স ঘনত্ব'
      }
    },
    {
      expression: 'B = (μ0 · μr · N · I) / l',
      description: {
        en: 'Magnetic field inside an ideal long solenoid',
        hi: 'आदर्श लंबी परिनालिका के अंदर चुंबकीय क्षेत्र',
        bn: 'আদর্শ দীর্ঘ সলিনয়েডের অভ্যন্তরে চৌম্বক ক্ষেত্র'
      }
    }
  ],
  workedExamples: [
    {
      problem: {
        en: 'An air-cored solenoid of length 0.4 m has 800 turns of copper wire and carries a current of 2.5 A. Calculate the magnetic field intensity H and flux density B at its center.',
        hi: '0.4 मीटर लंबी वायु-कोर परिनालिका में 800 फेरे हैं और इसमें 2.5 A की धारा प्रवाहित होती है। इसके केंद्र पर चुंबकीय तीव्रता H एवं फ्लक्स घनत्व B की गणना करें।',
        bn: '০.৪ মিটার দীর্ঘ একটি বায়ু-কোর বিশিষ্ট সলিনয়েডে ৮০০ পাক তার রয়েছে এবং এতে ২.৫ A কারেন্ট প্রবাহিত হয়। এর কেন্দ্রে চৌম্বক তীব্রতা H এবং ফ্লাক্স ঘনত্ব B নির্ণয় করো।'
      },
      solution: {
        en: `Given:
l = 0.4 m, N = 800, I = 2.5 A, μr = 1 (air), μ0 = 4π × 10⁻⁷ H/m

Step 1: Calculate Magnetic Field Intensity H:
H = (N · I) / l = (800 × 2.5) / 0.4 = 2000 / 0.4 = 5,000 A·t/m

Step 2: Calculate Magnetic Flux Density B:
B = μ0 · H = (4π × 10⁻⁷) × 5,000 = 6.283 × 10⁻³ Tesla = 6.283 mT (millitesla).`,
        hi: `दिया गया: l = 0.4 m, N = 800, I = 2.5 A, μr = 1

चरण 1: चुंबकीय तीव्रता H:
H = (N · I) / l = (800 × 2.5) / 0.4 = 5,000 A·t/m

चरण 2: फ्लक्स घनत्व B:
B = μ0 · H = (4π × 10⁻⁷) × 5000 = 6.283 mT।`,
        bn: `দেওয়া আছে: l = ০.৪ m, N = ৮০০, I = ২.৫ A, μr = ১

ধাপ ১: চৌম্বক ক্ষেত্র প্রাবল্য H:
H = (N · I) / l = (৮০০ × ২.৫) / ০.৪ = ৫,০০০ A·t/m

ধাপ ২: ফ্লাক্স ঘনত্ব B:
B = μ0 · H = (৪π × ১০⁻⁷) × ৫০০০ = ৬.২৮৩ mT।`
      }
    }
  ],
  quiz: [
    {
      question: {
        en: 'If the length of a solenoid is doubled while keeping the total turns (N) and current (I) constant, what happens to the internal magnetic field B?',
        hi: 'यदि फेरों की संख्या (N) और धारा (I) को स्थिर रखते हुए परिनालिका की लंबाई दोगुनी कर दी जाए, तो आंतरिक चुंबकीय क्षेत्र B पर क्या प्रभाव पड़ेगा?',
        bn: 'যদি মোট পাকসংখ্যা (N) এবং কারেন্ট (I) অপরিবর্তিত রেখে একটি সলিনয়েডের দৈর্ঘ্য দ্বিগুণ করা হয়, তবে ভেতরের চৌম্বক ক্ষেত্র B কেমন পরিবর্তিত হবে?'
      },
      options: {
        en: ['It doubles (2x)', 'It remains unchanged', 'It is halved (0.5x)', 'It becomes 4 times'],
        hi: ['दोगुना हो जाएगा', 'अपरिवर्तित रहेगा', 'आधा (0.5x) हो जाएगा', 'चार गुना हो जाएगा'],
        bn: ['দ্বিগুণ হবে', 'অপরিবর্তিত থাকবে', 'অর্ধেক (০.৫x) হবে', 'চার গুণ হবে']
      },
      correctAnswer: 2,
      explanation: {
        en: 'Since B = μ · (N · I) / l, the magnetic field is inversely proportional to the length l. Doubling l halves B.',
        hi: 'चूँकि B = μ · (N·I) / l, चुंबकीय क्षेत्र लंबाई l के व्युत्क्रमानुपाती होता है। l दोगुना करने पर B आधा हो जाता है।',
        bn: 'যেহেতু B = μ · (N·I) / l, চৌম্বক ক্ষেত্র দৈর্ঘ্যের ব্যস্তানুপাতিক। দৈর্ঘ্য দ্বিগুণ করলে B অর্ধেক হয়ে যায়।'
      }
    }
  ],
  flashcards: [
    {
      term: {
        en: 'Ampère\'s Circuital Law',
        hi: 'एम्पियर का परिपथीय नियम',
        bn: 'অ্যাম্পিয়ারের সার্কিটাল সূত্র'
      },
      definition: {
        en: '∮ B · dl = μ0 · I_enclosed. The closed loop line integral of magnetic field equals μ0 times the enclosed current.',
        hi: '∮ B · dl = μ0 · I_enclosed। किसी बंद लूप में चुंबकीय क्षेत्र का रेखीय समाकलन परिबद्ध धारा का μ0 गुना होता है।',
        bn: '∮ B · dl = μ0 · I_enclosed। কোনো বদ্ধ পথ বরাবর চৌম্বক ক্ষেত্রের রৈখিক সমাকলন আবদ্ধ মোট কারেন্টের μ0 গুণ।'
      }
    }
  ]
};
